apiVersion: v1
kind: Namespace
metadata:
  name: graylog

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-envs
  namespace: graylog
data:
  GRAYLOG_GID: '100'
  GRAYLOG_UID: '1009'
  TZ: 'Europe/Paris'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog-app
  namespace: graylog
  labels:
    app.kubernetes.io/name: graylog
    app.kubernetes.io/instance: graylog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: graylog
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: graylog
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: graylog-app
          image: graylog/graylog:4.0
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8989
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8989
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          ports:
            - containerPort: 8989
              hostPort: 8989
          envFrom:
            - configMapRef:
                name: graylog-envs
          volumeMounts:
            - mountPath: /config
              name: config-volume
            - mountPath: /downloads
              name: download-volume
            - mountPath: /tv
              name: tv-volume
      volumes:
        - name: config-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/ssd/containers/config/graylog
            type: DirectoryOrCreate
        - name: download-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/tank/shares/download
            type: DirectoryOrCreate
        - name: tv-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/tank/shares/videos/Séries
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: graylog-app
  namespace: graylog
  labels:
    app.kubernetes.io/name: graylog
spec:
  type: ClusterIP
  ports:
    - name: graylog
      port: 8989
      protocol: TCP
      targetPort: 8989
  selector:
    app.kubernetes.io/name: graylog

---

apiVersion: v1
kind: Endpoints
metadata:
  name: graylog-app
  namespace: graylog
  labels:
    app.kubernetes.io/name: graylog
    app.kubernetes.io/instance: graylog
subsets:
  - addresses:
      - ip: "192.168.1.25"
    ports:
      - name: graylog
        port: 8989
