apiVersion: v1
kind: Namespace
metadata:
  name: jackett

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: jackett-envs
  namespace: jackett
data:
  PGID: '100'
  PUID: '1006'
  TZ: 'Europe/Paris'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett-app
  namespace: jackett
  labels:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/instance: jackett
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jackett
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: jackett-app
          image: linuxserver/jackett
          imagePullPolicy: Always
          ports:
            - containerPort: 9117
              hostPort: 9117
          envFrom:
            - configMapRef:
                name: jackett-envs
          volumeMounts:
            - mountPath: /config
              name: config-volume
      volumes:
        - name: config-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/ssd/containers/config/jackett
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: jackett-app
  namespace: jackett
  labels:
    app.kubernetes.io/name: jackett
spec:
  type: ClusterIP
  ports:
    - name: jackett
      port: 9117
      protocol: TCP
      targetPort: 9117
  selector:
    app.kubernetes.io/name: jackett

---

apiVersion: v1
kind: Endpoints
metadata:
  name: jackett-app
  namespace: jackett
  labels:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/instance: jackett
subsets:
  - addresses:
      - ip: "192.168.1.25"
    ports:
      - name: jackett
        port: 9117
