apiVersion: v1
kind: Namespace
metadata:
  name: mineos

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mineos-envs
  namespace: mineos
data:
  USE_HTTPS: 'false'
  USER_UID: '1007'
  USER_PASSWORD: 'mc'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mineos-app
  namespace: mineos
  labels:
    app.kubernetes.io/name: mineos
    app.kubernetes.io/instance: mineos
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mineos
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mineos
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 600
      containers:
        - name: mineos-app
          image: hexparrot/mineos
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
              hostPort: 8443
            - containerPort: 25565
              hostPort: 25565
              protocol: TCP
            - containerPort: 25565
              hostPort: 25565
              protocol: UDP
          envFrom:
            - configMapRef:
                name: mineos-envs
          volumeMounts:
            - mountPath: /var/games/minecraft
              name: config-volume
      volumes:
        - name: config-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/ssd/containers/opt/mineos/config
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: mineos-app
  namespace: mineos
  labels:
    app.kubernetes.io/name: mineos
spec:
  type: ClusterIP
  ports:
    - name: mineos
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: minecraft
      port: 25565
      protocol: UDP
      targetPort: 25565
  selector:
    app.kubernetes.io/name: mineos

---

apiVersion: v1
kind: Endpoints
metadata:
  name: mineos-app
  namespace: mineos
  labels:
    app.kubernetes.io/name: mineos
    app.kubernetes.io/instance: mineos
subsets:
  - addresses:
      - ip: "192.168.1.25"
    ports:
      - name: mineos
        port: 8443
      - name: minecraft
        port: 25565
        protocol: TCP
      - name: minecraft-udp
        port: 25565
        protocol: UDP
