apiVersion: v1
kind: Namespace
metadata:
  name: overseerr

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: overseerr-envs
  namespace: overseerr
data:
  PGID: "100"
  PUID: "1012"
  TZ: "Europe/Paris"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr-app
  namespace: overseerr
  labels:
    app.kubernetes.io/name: overseerr
    app.kubernetes.io/instance: overseerr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: overseerr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: overseerr
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: overseerr-app
          image: linuxserver/overseerr:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 5055
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5055
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          ports:
            - containerPort: 5055
              hostPort: 5055
          envFrom:
            - configMapRef:
                name: overseerr-envs
          volumeMounts:
            - mountPath: /config
              name: config-volume
      volumes:
        - name: config-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/ssd/containers/config/overseerr
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: overseerr-app
  namespace: overseerr
  labels:
    app.kubernetes.io/name: overseerr
spec:
  type: ClusterIP
  ports:
    - name: overseerr
      port: 5055
      protocol: TCP
      targetPort: 5055
  selector:
    app.kubernetes.io/name: overseerr

---
apiVersion: v1
kind: Endpoints
metadata:
  name: overseerr-app
  namespace: overseerr
  labels:
    app.kubernetes.io/name: overseerr
    app.kubernetes.io/instance: overseerr
subsets:
  - addresses:
      - ip: "192.168.1.25"
    ports:
      - name: overseerr
        port: 5055
