apiVersion: v1
kind: Namespace
metadata:
  name: radarr

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-envs
  namespace: radarr
data:
  PGID: "100"
  PUID: "1004"
  TZ: "Europe/Paris"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-app
  namespace: radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: radarr-app
          image: linuxserver/radarr:develop
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 7878
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 7878
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          ports:
            - containerPort: 7878
              hostPort: 7878
          envFrom:
            - configMapRef:
                name: radarr-envs
          volumeMounts:
            - mountPath: /config
              name: config-volume
            - mountPath: /downloads
              name: download-volume
            - mountPath: /movies
              name: movies-volume
      volumes:
        - name: config-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/ssd/containers/config/radarr
            type: DirectoryOrCreate
        - name: download-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/tank/shares/download
            type: DirectoryOrCreate
        - name: movies-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/tank/shares/videos/Films/Films
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: radarr-app
  namespace: radarr
  labels:
    app.kubernetes.io/name: radarr
spec:
  type: ClusterIP
  ports:
    - name: radarr
      port: 7878
      protocol: TCP
      targetPort: 7878
  selector:
    app.kubernetes.io/name: radarr

---
apiVersion: v1
kind: Endpoints
metadata:
  name: radarr-app
  namespace: radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
subsets:
  - addresses:
      - ip: "192.168.1.25"
    ports:
      - name: radarr
        port: 7878
