apiVersion: v1
kind: Namespace
metadata:
  name: sonarr

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-envs
  namespace: sonarr
data:
  PGID: "100"
  PUID: "1005"
  TZ: "Europe/Paris"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-app
  namespace: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: sonarr-app
          image: linuxserver/sonarr:3.0.9.1549-ls172
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8989
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8989
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          ports:
            - containerPort: 8989
              hostPort: 8989
          envFrom:
            - configMapRef:
                name: sonarr-envs
          volumeMounts:
            - mountPath: /config
              name: config-volume
            - mountPath: /downloads
              name: download-volume
            - mountPath: /tv
              name: tv-volume
      volumes:
        - name: config-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/ssd/containers/config/sonarr
            type: DirectoryOrCreate
        - name: download-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/tank/shares/download
            type: DirectoryOrCreate
        - name: tv-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/tank/shares/videos/Séries
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-app
  namespace: sonarr
  labels:
    app.kubernetes.io/name: sonarr
spec:
  type: ClusterIP
  ports:
    - name: sonarr
      port: 8989
      protocol: TCP
      targetPort: 8989
  selector:
    app.kubernetes.io/name: sonarr

---
apiVersion: v1
kind: Endpoints
metadata:
  name: sonarr-app
  namespace: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr
subsets:
  - addresses:
      - ip: "192.168.1.25"
    ports:
      - name: sonarr
        port: 8989
