apiVersion: v1
kind: Namespace
metadata:
  name: tautulli

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: tautulli-envs
  namespace: tautulli
data:
  PGID: '100'
  PUID: '1009'
  TZ: 'Europe/Paris'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli-app
  namespace: tautulli
  labels:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: tautulli-app
          image: tautulli/tautulli:v2.9.4
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8181
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8181
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          ports:
            - containerPort: 8181
              hostPort: 8181
          envFrom:
            - configMapRef:
                name: tautulli-envs
          volumeMounts:
            - mountPath: /config
              name: config-volume
      volumes:
        - name: config-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/ssd/containers/config/tautulli
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: tautulli-app
  namespace: tautulli
  labels:
    app.kubernetes.io/name: tautulli
spec:
  type: ClusterIP
  ports:
    - name: tautulli
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    app.kubernetes.io/name: tautulli

---

apiVersion: v1
kind: Endpoints
metadata:
  name: tautulli-app
  namespace: tautulli
  labels:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
subsets:
  - addresses:
      - ip: "192.168.1.25"
    ports:
      - name: tautulli
        port: 8181
